name: Deploy to Lightsail

on:
  push:
    branches:
      - main # or master, depending on your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or your Node.js version

      - name: Install Dependencies
        run: npm ci

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_IP }} # Your Lightsail IP
          username: bitnami # or your username
          key: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }} # Your private key
          script: |
            cd stripe-server/ # Adjust to your app directory
            pm2 stop stripe-server
            git pull origin main
            npm install
            pm2 start stripe-server
            sudo systemctl restart nginx